sudo: false
language: python
python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"
install:
  - travis_retry pip install --upgrade pip -q
  - travis_retry pip install nose coverage flake8 flake8-blind-except flake8-debugger flake8-print flake8-quotes pep8-naming frosted isort coveralls -q
script:
  - python setup.py nosetests --with-coverage
after_success:
  - flake8 --show-source fake_useragent
  - frosted -r fake_useragent
  - isort --check-only -rc fake_useragent --diff
  - travis_retry coveralls
