language: python
python:
  - "3.4"
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"
  - "pypy"
install:
  - pip install coverage nose flake8 coveralls
script:
  - flake8 --show-source fake_useragent
  - frosted -r fake_useragent
  - isort --check-only -rc fake_useragent --diff
  - python setup.py nosetests --with-coverage
after_success:
  - coveralls
