sudo: false
language: python
python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"
install:
  - travis_retry pip install -q flake8 flake8-blind-except flake8-quotes flake8-tuple pep8-naming isort coveralls coverage
  - pip freeze | grep coverage
script:
  - python setup.py nosetests --verbosity=2 --nocapture --nologcapture --cover-package=fake_useragent --with-coverage --cover-erase
after_success:
  - flake8 --show-source fake_useragent
  - isort --check-only -rc fake_useragent --diff
  - travis_retry coveralls
